name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run steep
        run: bundle exec steep check

      - name: Run rspec
        run: bundle exec rspec
